use_frameworks!

pod 'Zip', :git => 'git@github.com:marmelroy/Zip.git', :branch => 'swift3.0', :submodules => true

target 'iOSDFULibrary_Example' do
  pod 'iOSDFULibrary', :path => '../'
end

target 'iOSDFULibrary_Tests' do
  pod 'iOSDFULibrary', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

